---
- name: Get instances facts
  ec2_instance_facts:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    region: "{{ region }}"
  register: result

- name: Instances ID
  debug:
    msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
  loop: "{{ result.instances }}"

- name: Upload public key to AWS
  ec2_key:
    name: "{{ key_name }}"
    key_material: "{{ lookup('file', '{{user}}{{ key_name }}.pub') }}"
    region: "{{ region }}"
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"

- name: Create security group
  ec2_group:
    name: "{{ sec_group }}"
    description: "Sec group for app {{ id }}"
    # vpc_id: 12345
    region: "{{ region }}"
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on ssh port
  register: result_sec_group